import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fernando
 */
public class Karyawan extends javax.swing.JFrame {

    /**
     * Creates new form Karyawan
     */
    public Karyawan() throws SQLException, ClassNotFoundException, ParseException {
        initComponents();
        
        String sql = "select no_meja, nama_paket, tanggal, qty from tbl_pesan, "
                + "tbl_paket where tbl_pesan.id_paket = tbl_paket.id_paket;";
        ArrayList<pesanan> psns = new ArrayList<pesanan>();
        PreparedStatement pstm = AppMain.conn.prepareStatement(sql);
        ResultSet rs = pstm.executeQuery();
        Date date = new Date();
        lblTglPesan.setText(date.toString());
        
        while(rs.next()){
            System.out.println("Sucesss");
            pesanan psn = new pesanan(
                rs.getString("no_meja"),
                rs.getString("nama_paket"),
                rs.getString("tanggal"),
                rs.getInt("qty")
            );
            psns.add(psn);
        }
        
        System.out.println(psns.size());
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
       
        for(pesanan ps : psns){
            System.out.println(ps.getNamaPaket());
            model.addRow(new Object[]{ps.getNoMeja(), ps.getNamaPaket(), ps.getTanggal(), ps.getQty()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tanggal = new javax.swing.JLabel();
        lblTglPesan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Meja", "Nama Paket", "Tanggal", "Qty"
            }
        ));
        jScrollPane1.setViewportView(table);

        tanggal.setText("Tanggal Pesan:");

        lblTglPesan.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tanggal)
                        .addGap(32, 32, 32)
                        .addComponent(lblTglPesan)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggal)
                    .addComponent(lblTglPesan))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTglPesan;
    private javax.swing.JTable table;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}

class pesanan{
    String no_meja;
    String nama_paket;
    String tanggal;
    int qty;
    public pesanan(String no_meja, String nama_paket, String tanggal, int qty){
        this.no_meja = no_meja;
        this.nama_paket = nama_paket;
        this.tanggal = tanggal;
        this.qty = qty;
    }
    public String getNoMeja(){
        return no_meja;
    }
    
    public String getNamaPaket(){
        return nama_paket;
    }
    
    public String getTanggal(){
        return tanggal;
    }
    
    public int getQty(){
        return qty;
    }
}
