import java.awt.TextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utild.ConnectionUtils;

/**
 *
 * @author fernando
 */
public class UIMenu extends javax.swing.JFrame {
 

    /**
     * Creates new form UIMenu
     */
    private String nopaket;
    private int count = 0;
    public UIMenu() throws ClassNotFoundException, SQLException {
        initComponents();
        JOptionPane.showMessageDialog(null,"Selamat Datang di Restoran TANDO \n" +"Silahkan Pilih Menu pesanan Anda.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnorderbaru = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnpaket1 = new javax.swing.JButton();
        btnpaket2 = new javax.swing.JButton();
        btnpaket3 = new javax.swing.JButton();
        btnpaket4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        onama1 = new javax.swing.JTextField();
        onama2 = new javax.swing.JTextField();
        onama3 = new javax.swing.JTextField();
        onama4 = new javax.swing.JTextField();
        oharga1 = new javax.swing.JTextField();
        oharga2 = new javax.swing.JTextField();
        oharga3 = new javax.swing.JTextField();
        oharga4 = new javax.swing.JTextField();
        txtBanyak = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnprosestransaksi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnhitung = new javax.swing.JButton();
        txtBayar = new javax.swing.JTextField();
        kembali = new javax.swing.JTextField();
        btnorder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnorderbaru.setText("Order Baru");
        btnorderbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderbaruActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        jLabel1.setText("RESTORAN TANDO");

        jLabel2.setText("Paket Menu");

        btnpaket1.setText("Paket Sate Ayam");
        btnpaket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaket1ActionPerformed(evt);
            }
        });

        btnpaket2.setText("Paket Ayam Bakar");
        btnpaket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaket2ActionPerformed(evt);
            }
        });

        btnpaket3.setText("Paket Steak");
        btnpaket3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaket3ActionPerformed(evt);
            }
        });

        btnpaket4.setText("Paket Ikan Bakar");
        btnpaket4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaket4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Daftar Menu yang Dipesan:");

        jLabel4.setText("Nama");

        jLabel5.setText("Harga(Rp)");

        jLabel6.setText("Banyaknya");

        jLabel7.setText("Total");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnprosestransaksi.setText("Proses Transaksi");
        btnprosestransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosestransaksiActionPerformed(evt);
            }
        });

        jLabel9.setText("Bayar(Rp)");

        jLabel10.setText("Kembali(Rp)");

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        btnorder.setText("ORDER");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnorderbaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(btnpaket1)
                                                .addGap(135, 135, 135)
                                                .addComponent(btnpaket2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel4)
                                                    .addComponent(onama3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(onama2)
                                                    .addComponent(onama1)
                                                    .addComponent(onama4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(oharga1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(oharga4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(oharga3)
                                                        .addComponent(oharga2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(51, 51, 51)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(txtBanyak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(10, 10, 10)))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(btnpaket3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(119, 119, 119)
                                                .addComponent(btnpaket4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addGap(57, 57, 57))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(84, 84, 84)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel7)
                                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnhitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnprosestransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtBayar)
                                                    .addComponent(kembali)
                                                    .addComponent(txtTotal))
                                                .addGap(71, 71, 71)
                                                .addComponent(btnorder, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(472, 472, 472)
                                .addComponent(jLabel2)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnorderbaru)
                        .addComponent(btnbatal)))
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnpaket1)
                    .addComponent(btnpaket2)
                    .addComponent(btnpaket3)
                    .addComponent(btnpaket4))
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oharga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBanyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oharga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onama3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oharga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onama4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oharga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnprosestransaksi)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(7, 7, 7)
                                .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhitung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnorder))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel9)))))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprosestransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosestransaksiActionPerformed
        // TODO add your handling code here:
        int totalHargapaket = Integer.valueOf(oharga1.getText()) + Integer.valueOf(oharga2.getText())
            +Integer.valueOf(oharga3.getText()) + Integer.valueOf(oharga4.getText());
        
        int totHarga = Integer.valueOf(txtBanyak.getText()) * totalHargapaket;
        txtTotal.setText(String.valueOf(totHarga));
        
    }//GEN-LAST:event_btnprosestransaksiActionPerformed

    
    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
              if (JOptionPane.showConfirmDialog(null,
        "Yakin nggak mau pesan makanannya?", "Pintu Keluar",
        JOptionPane.YES_NO_OPTION)==
        JOptionPane.YES_OPTION){
         System.exit(0);
         }
    }//GEN-LAST:event_btnbatalActionPerformed

    private ArrayList<String> getNamaMakanan(int nopaket){
        ArrayList<String> listmakanan=new ArrayList<String>();
        
        String sql = "select nama_makanan, harga from tbl_makanan where id_paket=?";
        PreparedStatement pstm;
        try {
            pstm = AppMain.conn.prepareStatement(sql);
            pstm.setInt(1, nopaket);
        ResultSet rs = pstm.executeQuery();
        while(rs.next()){
            String namamakan = rs.getString("nama_makanan");
            listmakanan.add(namamakan);
            int harga = rs.getInt("harga"); }
        } catch (SQLException ex) {
            Logger.getLogger(UIMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        return listmakanan;
        
    }
    
    private ArrayList<Integer> getHargaMakanan(int nopaket){
        ArrayList<Integer> hargamakan=new ArrayList<Integer>();
        
        String sql = "select nama_makanan, harga from tbl_makanan where id_paket=?";
        PreparedStatement pstm;
        try {
            pstm = AppMain.conn.prepareStatement(sql);
            pstm.setInt(1, nopaket);
        ResultSet rs = pstm.executeQuery();
        while(rs.next()){
            String namamakan = rs.getString("nama_makanan");
            
            int harga = rs.getInt("harga");
        hargamakan.add(harga);}
        } catch (SQLException ex) {
            Logger.getLogger(UIMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        return hargamakan;
        
    }
    private void btnpaket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaket1ActionPerformed
        // TODO add your handling code here:
        nopaket="1";
        count++;
        System.out.println("Success");
       try{
                String sql = "insert into tbl_trx values(?, ?, ?, ?)";
                PreparedStatement pstm = AppMain.conn.prepareStatement(sql);
                pstm.setInt(1, count);
                pstm.setString(2, nopaket);
                pstm.setString(3, "Sate Ayam");
                pstm.setInt(4, 0);
                pstm.executeUpdate();
            }catch(SQLException e){
                
            }
        
        onama1.setText( getNamaMakanan(1).get(0));
        oharga1.setText(getHargaMakanan(1).get(0).toString());
        onama2.setText( getNamaMakanan(1).get(1));
        oharga2.setText(getHargaMakanan(1).get(1).toString());        
        onama3.setText( getNamaMakanan(1).get(2));
        oharga3.setText(getHargaMakanan(1).get(2).toString());
        onama4.setText( getNamaMakanan(1).get(3));
        oharga4.setText(getHargaMakanan(1).get(3).toString());
        
        
       
        
    }//GEN-LAST:event_btnpaket1ActionPerformed

    private void btnorderbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderbaruActionPerformed
        // TODO add your handling code here:
        onama1.setText("");
        onama2.setText("");
        onama3.setText("");
        onama4.setText("");
        oharga1.setText("");
        oharga2.setText("");
        oharga3.setText("");
        oharga4.setText("");
        txtTotal.setText("");
        txtBayar.setText("");
        kembali.setText("");
    }//GEN-LAST:event_btnorderbaruActionPerformed

    private void btnpaket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaket2ActionPerformed
        // TODO add your handling code here:
        nopaket="2";
        count++;
        System.out.println("Success");
       try{
                String sql = "insert into tbl_trx values(?, ?, ?, ?)";
                PreparedStatement pstm = AppMain.conn.prepareStatement(sql);
                pstm.setInt(1, count);
                pstm.setString(2, nopaket);
                pstm.setString(3, "Ayam Bakar");
                pstm.setInt(4, 0);
                pstm.executeUpdate();
            }catch(SQLException e){
                
            }
        onama1.setText( getNamaMakanan(2).get(0));
        oharga1.setText(getHargaMakanan(2).get(0).toString());
        onama2.setText( getNamaMakanan(2).get(1));
        oharga2.setText(getHargaMakanan(2).get(1).toString());        
        onama3.setText( getNamaMakanan(2).get(2));
        oharga3.setText(getHargaMakanan(2).get(2).toString());
        onama4.setText( getNamaMakanan(2).get(3));
        oharga4.setText(getHargaMakanan(2).get(3).toString());
        
        
       
        
    }//GEN-LAST:event_btnpaket2ActionPerformed

    private void btnpaket3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaket3ActionPerformed
        // TODO add your handling code here:
        nopaket="3";
        count++;
        System.out.println("Success");
        try{
            String sql = "insert into tbl_trx values(?, ?, ?, ?)";
            PreparedStatement pstm = AppMain.conn.prepareStatement(sql);
            pstm.setInt(1, count);
            pstm.setString(2, nopaket);
            pstm.setString(3, "Steak");
            pstm.setInt(4, 0);
            pstm.executeUpdate();
        }catch(SQLException e){}
        onama1.setText( getNamaMakanan(3).get(0));
        oharga1.setText(getHargaMakanan(3).get(0).toString());
        onama2.setText( getNamaMakanan(3).get(1));
        oharga2.setText(getHargaMakanan(3).get(1).toString());        
        onama3.setText( getNamaMakanan(3).get(2));
        oharga3.setText(getHargaMakanan(3).get(2).toString());
        onama4.setText( getNamaMakanan(3).get(3));
        oharga4.setText(getHargaMakanan(3).get(3).toString());
        
        
       
        
    }//GEN-LAST:event_btnpaket3ActionPerformed

    private void btnpaket4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaket4ActionPerformed
        // TODO add your handling code here:
        nopaket="4";
        count++;
        System.out.println("Success");
       try{
                String sql = "insert into tbl_trx values(?, ?, ?, ?)";
                PreparedStatement pstm = AppMain.conn.prepareStatement(sql);
                pstm.setInt(1, count);
                pstm.setString(2, nopaket);
                pstm.setString(3, "Ikan Bakar");
                pstm.setInt(4, 0);
                pstm.executeUpdate();
            }catch(SQLException e){
                
            }
        onama1.setText( getNamaMakanan(4).get(0));
        oharga1.setText(getHargaMakanan(4).get(0).toString());
        onama2.setText( getNamaMakanan(4).get(1));
        oharga2.setText(getHargaMakanan(4).get(1).toString());        
        onama3.setText( getNamaMakanan(4).get(2));
        oharga3.setText(getHargaMakanan(4).get(2).toString());
        onama4.setText( getNamaMakanan(4).get(3));
        oharga4.setText(getHargaMakanan(4).get(3).toString());
        
        
       
        
    }//GEN-LAST:event_btnpaket4ActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        
        if(txtBayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Masukan Uang Dahulu");
        }else{
            int a1 = Integer.parseInt(txtTotal.getText());
            int a2 = Integer.parseInt(txtBayar.getText());
            int hasil= a2-a1;
            if(hasil<0){
                JOptionPane.showMessageDialog(rootPane, "Uang Kurang");}
   
            else{  
            kembali.setText(""+hasil);
        }
        }   
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        if(txtBayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Transaksi Belum Diisi");
        }else{
            AppMain.curQty = Integer.parseInt(txtBanyak.getText());
            new UIForm().setVisible(true);
        }
        AppMain.curTrx  = Integer.parseInt(nopaket);
    }//GEN-LAST:event_btnorderActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnorder;
    private javax.swing.JButton btnorderbaru;
    private javax.swing.JButton btnpaket1;
    private javax.swing.JButton btnpaket2;
    private javax.swing.JButton btnpaket3;
    private javax.swing.JButton btnpaket4;
    private javax.swing.JButton btnprosestransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField oharga1;
    private javax.swing.JTextField oharga2;
    private javax.swing.JTextField oharga3;
    private javax.swing.JTextField oharga4;
    private javax.swing.JTextField onama1;
    private javax.swing.JTextField onama2;
    private javax.swing.JTextField onama3;
    private javax.swing.JTextField onama4;
    private javax.swing.JTextField txtBanyak;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
